Q1:
 Executing an empty throw statement outside a catch  handler calls function terminate, which abandons exception processing and terminates the program immediately. 
 
 
Q2:YES!
  Control resumes with the first statement after the last catch handler following the try block. This is known as the termination model of exception handling. 
  
Q3: 
  type "make",and then "main" will be produced.
  enter"./main",and you'll see the output.
